### ISSUE TITLE
up/down arrow

### ISSUE THREAD

**Issue by flopp26** [fengyuanchen/pickerjs#10]
Hi, thanks you for this cool library :)

do you intend to add an up/down arrow as an option for each column, IMO is more intuitive on the desktop, for now I use the next() and prev(), but is not "design"
thanks

**Comment by fengyuanchen** [comment]
@flopp26 You can use the `controls` option (as of v1.2.0) for this feature now.

**Comment by flopp26** [comment]
Thanks you so much for your works
