### ISSUE TITLE
bug? with format and init date

### ISSUE THREAD

**Issue by flopp26** [fengyuanchen/pickerjs#11]
Hi,

I init picker with

<code>
date: 2018-07-05 12:00,
format: 'YYYY-MM-DD HH:mm',
</code>

when I use getDate(), I get :
<code>2018-07-05T10:00:35.695Z</code>

so everything is ok, but when I use this :

<code>
date: 2018-07-05 12:00,
format: 'HH:mm',
</code>

I get the current date and not the date initialized.

what do you think ?

**Comment by fengyuanchen** [comment]
Just use `getDate(true)`.

> https://github.com/fengyuanchen/pickerjs#getdateformatted
