### ISSUE TITLE
Bug: DD-MM-YYYY HH:mm format Year has an additional - in front

### ISSUE THREAD

**Issue by somebodydudu** [fengyuanchen/pickerjs#18]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

In your Sample Page: 
**set value 25-10-2018 15:45
set date format DD-MM-YYYY HH:mm
then click Show, 
Year got - in front**
## Environment

<pre><code>
Picker.js version: X.Y.Z

Browser:
- [x ] Chrome (desktop) version XX
- [x ] Chrome (Android) version XX
- [ x] Chrome (iOS) version XX
- [ x] Firefox version XX
- [ x] Safari (desktop) version XX
- [ x] Safari (iOS) version XX
- [ x] IE version XX
- [ x] Edge version XX

Others:

</code></pre>

**Comment by somebodydudu** [comment]
![pickerjsissue](https://user-images.githubusercontent.com/32233920/47472680-2aa99c80-d842-11e8-8633-aca6729d7c49.PNG)

**Comment by somebodydudu** [comment]
DD/MM/YYYY is working, but not with HH:mm, suspect it might be the parse for the SPACE after YYYY got issue

**Comment by fengyuanchen** [comment]
See #17
