### ISSUE TITLE
How to prevent default behaviour (printing picked time to el) when picking date/time?

### ISSUE THREAD

**Issue by bnjmnjns** [fengyuanchen/pickerjs#4]
Hi,

I'm wondering if there's a way to block the default behaviour of printing out the picked time to the select element on the pick event? I'm using momentjs to handle all time functionality and would prefer to use moment to print out the date to the element. 

It would also allow you to select a larger element as the trigger element to without it wiping out your markup. 

Thanks!

**Comment by fengyuanchen** [comment]
```js
const picker = new Picker(element, {
  pick(event) {
    event.preventDefault();
    picker.hide();
  },
});
```
